### PR TITLE
Add "Live Instances", split "Technology" into it's own page

### PR DESCRIPTION
**Pull request by cmc333333**
This is prep for a following PR which will expand on the repositories section, which will include 18f repos and the now-shared fr-notices repo.

See individual changesets for details. Looks like: http://cmc333333.github.io/eRegulations/

### CODE REVIEW

**Comment by ascott1** [comment]
:boom: Great changes. Thanks @cmc333333

**Comment by ascott1** [comment]
Oops, except the `/technology` link isn't working github pages.

**Comment by ascott1** [comment]
@cmc333333 I think `technology.html` should actually be `technology.md` (?)

**Comment by cmc333333** [comment]
@ascott1 sorry about that! Should be fixed in #11

**Pull request merged**
