### PR TITLE
Expanding theming advice with content from regulations-site readme

### PR DESCRIPTION
**Pull request by brittag**
Consolidating https://github.com/18F/regulations-site#customization into this page (plus some small improvements and additions based on Slack discussions), so that we can have two pages to look for advice about theming (this one and https://atf-eregs.readthedocs.org/en/latest/customization.html) rather than three.

### CODE REVIEW

**Comment by cmc333333** [comment]
:+1:

**Comment by cmc333333** [comment]
Hm, this doesn't appear to have built :/

**Comment by brittag** [comment]
Aww! It works ok in my local copy, I don't see a build error in settings, and I didn't get a build warning email, so I'm not sure what's happening. :(

**Comment by cmc333333** [comment]
#34 resolved

**Pull request merged**
