### PR TITLE
easy to easier

### PR DESCRIPTION
**Pull request by ascott1**
Related to [regulations-site #708](https://github.com/cfpb/regulations-site/pull/708). This changes an instance of "easy" to "easier" to prevent the assumption that we are changing regulation text in any way.

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
There's another easy in the readme and in _includes/index.md.

**Comment by ascott1** [comment]
Good catch on the README! The `easy navigation` in `_includes/index.md` is ok to stay in.

**Comment by KimberlyMunoz** [comment]
Great. Merging!

**Comment by ascott1** [comment]
Yay! Thanks!

**Pull request merged**
